// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewnmsycswckkssoppfem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3bm1zeWNzd2Nra3Nzb3BwZmVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDY1MDgsImV4cCI6MjA3Mzc4MjUwOH0.6mAveOFYp_T2u9B6iC8mS1yvPcVVAqmO3vNguW_6gKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});